mode: "local" # "local" means local database without credentials, "online" needs the credeantials in database-section

database:
  online:
    url: "jdbc:mysql://your-online-host:3306/proddb"
    user: "produser"
    password: "prodpassword"